import os
import asyncio
import numpy as np
import sounddevice as sd
import pyttsx3
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process, LLM
from faster_whisper import WhisperModel
import litellm
litellm.cache = None

# 1. Load environment keys
load_dotenv()

# ============================================================
# 2. VOICE ENGINE SETUP
# ============================================================

# Load both Whisper models once at startup
print("🔄 Loading Whisper models...")
whisper_small = WhisperModel("small", device="cpu", compute_type="int8")
whisper_medium = WhisperModel("medium", device="cpu", compute_type="int8")
print("✅ Whisper models loaded.")

# TTS engine
tts_engine = pyttsx3.init()
tts_engine.setProperty("rate", 175)  # speaking speed

def detect_complexity(audio_np):
    """
    Choose Whisper model based on noise level and estimated word count.
    High noise or long speech = medium. Clean/short = small.
    """
    noise_level = np.std(audio_np)
    estimated_words = np.count_nonzero(np.abs(audio_np) > 0.02) / 16000 * 2.5

    if noise_level > 0.05 or estimated_words > 15:
        print("🧠 Complexity: HIGH → Using Whisper medium")
        return "medium"
    else:
        print("🧠 Complexity: LOW → Using Whisper small")
        return "small"

def listen(duration=10):
    """
    Record audio from microphone and transcribe using adaptive Whisper model.
    """
    print(f"🎤 Listening for {duration} seconds... (speak now)")
    audio = sd.rec(
        int(duration * 16000),
        samplerate=16000,
        channels=1,
        dtype="float32"
    )
    sd.wait()
    audio_np = audio.flatten()

    # Adaptive model selection
    complexity = detect_complexity(audio_np)
    model = whisper_medium if complexity == "medium" else whisper_small

    print("⏳ Transcribing...")
    segments, _ = model.transcribe(audio_np, beam_size=1)
    text = " ".join([s.text for s in segments]).strip()
    print(f"📝 You said: {text}")
    return text

def speak(text):
    """
    Convert text to speech using pyttsx3 (offline, instant).
    """
    print(f"🔊 NOVA: {text}")
    tts_engine.say(text)
    tts_engine.runAndWait()

# ============================================================
# 3. CONFIGURE AI BRAINS
# ============================================================

researcher_brain = LLM(
    model="groq/llama-3.3-70b-versatile",
    api_key=os.environ.get("GROQ_API_KEY")
)

coder_brain = LLM(
    model="groq/llama-3.3-70b-versatile",
    api_key=os.environ.get("GROQ_API_KEY")
)

architect_brain = LLM(
    model="openai/meta-llama-3.3-70b-instruct",
    base_url="https://models.inference.ai.azure.com",
    api_key=os.environ.get("GITHUB_TOKEN")
)

reviewer_brain = LLM(
    model="groq/llama-3.3-70b-versatile",
    api_key=os.environ.get("GROQ_API_KEY")
)

# ============================================================
# 4. DEFINE CREW AGENTS
# ============================================================

researcher_agent = Agent(
    role="Lead Systems Researcher",
    goal="Gather implementation guidelines, technical docs, and structured research for the given task.",
    backstory="An analytical researcher who compiles precise technical blueprints.",
    llm=researcher_brain,
    verbose=True,
    allow_delegation=False
)

coder_agent = Agent(
    role="Senior Software Automation Engineer",
    goal="Translate project blueprints into robust, production-ready Python code.",
    backstory="A terminal developer who writes clean, well-commented code.",
    llm=coder_brain,
    verbose=True,
    allow_delegation=False
)

reviewer_agent = Agent(
    role="Principal QA Software Architect",
    goal="Audit code outputs for security, logic flaws, and style issues.",
    backstory="A meticulous code analyst who writes detailed audit reports.",
    llm=reviewer_brain,
    verbose=True,
    allow_delegation=False
)

# ============================================================
# 5. DEFINE TASKS (dynamic — uses voice input as topic)
# ============================================================

def build_crew(topic):
    task_research = Task(
        description=(
            f"Research the core requirements for: {topic}. "
            "Compile your structured results into a precise Markdown blueprint document."
        ),
        expected_output="A comprehensive Markdown technical specification.",
        agent=researcher_agent,
        output_file="system_blueprint.md"
    )

    task_coding = Task(
        description=(
            "Analyze the system_blueprint.md file generated by the researcher. "
            "Write a fully functional, beautifully commented, clean Python application. "
            "Build in robust error exception loops."
        ),
        expected_output="A production-ready Python script.",
        agent=coder_agent,
        output_file="system_monitor.py"
    )

    task_review = Task(
        description=(
            "Perform a thorough white-box security and style review on the completed script. "
            "Identify potential bugs, logic flaws, or dependency problems. "
            "Write an audit log with findings and suggestions."
        ),
        expected_output="A well-structured QA audit log.",
        agent=reviewer_agent,
        output_file="audit_log.md"
    )

    crew = Crew(
        agents=[researcher_agent, coder_agent, reviewer_agent],
        tasks=[task_research, task_coding, task_review],
        process=Process.sequential,
        verbose=True
    )

    return crew

# ============================================================
# 6. MAIN — VOICE LOOP
# ============================================================

if __name__ == "__main__":
    print("\n🚀 [NOVA ENGINE INITIALIZED]")
    speak("NOVA is ready. Please speak your task.")

    # Get voice input
    topic = listen(duration=10)

    if not topic:
        speak("I did not catch that. Please try again.")
    else:
        speak(f"Understood. Starting crew for: {topic}")
        print(f"\n📋 Task: {topic}")

        crew = build_crew(topic)
        result = crew.kickoff()

        print("\n" + "="*60)
        print("✅ [MISSION ACCOMPLISHED] Crew run completed successfully!")
        print("📂 Created: system_blueprint.md, system_monitor.py, audit_log.md")
        print("="*60)

        speak("Mission accomplished. Output files have been created.")
